# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gtk 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "gtk"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Patrick Hanevold"]
  s.date = "2014-06-10"
  s.description = "GTK FFI bindings for Ruby"
  s.email = "patrick.hanevold@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/custom_cell_renderer.rb",
    "gtk.gemspec",
    "lib/gtk.rb",
    "lib/gtk/bin.rb",
    "lib/gtk/buttons_type.rb",
    "lib/gtk/cell_renderer.rb",
    "lib/gtk/cell_renderer_text.rb",
    "lib/gtk/container.rb",
    "lib/gtk/dialog_flags.rb",
    "lib/gtk/g_type.rb",
    "lib/gtk/list_store.rb",
    "lib/gtk/message_dialog.rb",
    "lib/gtk/message_type.rb",
    "lib/gtk/selection_mode.rb",
    "lib/gtk/style_context.rb",
    "lib/gtk/tree_iter.rb",
    "lib/gtk/tree_model.rb",
    "lib/gtk/tree_path.rb",
    "lib/gtk/tree_selection.rb",
    "lib/gtk/tree_store.rb",
    "lib/gtk/tree_view.rb",
    "lib/gtk/tree_view_column.rb",
    "lib/gtk/window.rb",
    "lib/gtk/window_position.rb",
    "lib/gtk/window_type.rb",
    "spec/gtk_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/patrickhno/gtk"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.0"
  s.summary = "GTK FFI bindings for Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_development_dependency(%q<gtk>, [">= 0"])
      s.add_development_dependency(%q<cairo>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<bacon>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<gtk>, [">= 0"])
      s.add_dependency(%q<cairo>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<bacon>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<gtk>, [">= 0"])
    s.add_dependency(%q<cairo>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<bacon>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

